### ISSUE TITLE
Possible duplicate of dired-filter package

### ISSUE THREAD

**Issue by Fuco1** [mattiasb/dired-hide-dotfiles#2]
Hi.

I found this in the "emacs weekly news" and just want to point out that there already is a solution in the `dired-filter` package (https://github.com/Fuco1/dired-hacks#dired-filter), which on top of the "dotfile" filter provdes dozens of others.

If this is just a "training" package, no harm done, but I think we should try to lower the duplication (the Emacs community suffers from this problem a lot).

**Comment by mattiasb** [comment]
I tried that package out first, but it did a lot more than I wanted and traded away some ux for that power.

See [here](https://github.com/melpa/melpa/pull/4614#issuecomment-284948605) for the discussion.
