### ISSUE TITLE
When turn on `global-auto-revert-mode`, it keeps showing message in echo area

### ISSUE THREAD

**Issue by snowman** [mattiasb/dired-hide-dotfiles#4]
## description

It keeps showing following messages in echo area even though when not in `dired` buffer when `global-auto-revert-mode` is turned on:

```text
Marking matching files...
6 matching files marked
Killed 6 lines.
```

https://github.com/mattiasb/dired-hide-dotfiles/blob/b715f643ec805b3b8aca334595e6589320f04a49/dired-hide-dotfiles.el#L59-L63

https://github.com/mattiasb/dired-hide-dotfiles/blob/b715f643ec805b3b8aca334595e6589320f04a49/dired-hide-dotfiles.el#L66

This becomes annoying when you have lots of `dired` buffer opened in the background especially when you are editing your files.

## The steps to reproduce:

```sh
## TODO: should rewrite the scripts into run.sh file
git clone https://github.com/mattiasb/dired-hide-dotfiles /tmp/dired-hide-dotfiles
\rm -rf /tmp/playground && \mkdir -p /tmp/playground
## TODO: should rewrite into debug.el file
\emacs -Q -nw --eval="(custom-set-faces '(default ((t (:family \"Source Code Pro\" :foundry \"ADBO\" :slant normal :weight normal :height 233 :width normal)))))" \
       -l "/tmp/dired-hide-dotfiles/dired-hide-dotfiles.el" \
       --eval="(setq global-auto-revert-non-file-buffers t)" \
       --eval="(global-auto-revert-mode)" \
       --eval="(add-hook 'dired-mode-hook #'dired-hide-dotfiles-mode)" \
       /tmp/playground
```

Then switch to other buffer like `*scratch*`, and runs `$ touch /tmp/playground/new-file` in the command line.

This will result in the `dired` buffer `/tmp/playground` runs `revert-buffer` which runs the hook `dired-after-readin-hook`.

## possible solution

```elisp
(defun dired-hide-dotfiles--hide ()
  "Hide all dot-files in the current `dired' buffer."

  (when dired-hide-dotfiles-mode
    (let ((inhibit-message t))
      (dired-mark-files-regexp "^\\.")
      (dired-do-kill-lines))))
```

```text
inhibit-message is a variable defined in C source code.

Documentation
Non-nil means calls to message are not displayed.

They are still logged to the *Messages* buffer.
```

**Comment by mattiasb** [comment]
Hm, looking at `dired-omit-mode` it doesn't do anything like that (it actually displays the message in the echo area). 

However I kind of like your suggestion and will just roll with it! :)

**Comment by mattiasb** [comment]
Actually. Looking at `dired-omit` they just make it configurable. I'll go with that instead.

**Comment by mattiasb** [comment]
You can now set `dired-hide-dotfiles-verbose` to `nil` to hide the `minibuffer` spam, just like in `dired-omit-mode`.

**Comment by snowman** [comment]
Thanks for the commit, loves it :) :+1:

**Comment by mattiasb** [comment]
Woop! :)
