### ISSUE TITLE
README.md example config to hide dotfiles does not work

### ISSUE THREAD

**Issue by snowman** [mattiasb/dired-hide-dotfiles#5]
## description
Comment below code from file `dired-hide-dotfiles.el` first:
```elisp
;;; (add-hook 'dired-after-readin-hook 'dired-hide-dotfiles--hide)
```

https://github.com/mattiasb/dired-hide-dotfiles/blob/b715f643ec805b3b8aca334595e6589320f04a49/README.md#L20-L30

This *always* results in the following messages when open new `dired` buffer:
```text
Marking matching files...
0 matching files marked
Killed 0 lines.
```

*NOTE*: *0* matching files marked, even when there are dotfiles exist.

## reproduce
1. Comment below code from file `dired-hide-dotfiles.el`:
```lisp
;;; (add-hook 'dired-after-readin-hook 'dired-hide-dotfiles--hide)
```
2. File `debug.el`
```lisp
(custom-set-faces
 '(default ((t (
                :family "Source Code Pro"
                :foundry "ADBO"
                :slant normal
                :weight normal
                :height 233
                :width normal)))))

(load "/tmp/dired-hide-dotfiles/dired-hide-dotfiles.el")
(add-hook 'dired-mode-hook #'dired-hide-dotfiles-mode)
```
3. File `debug-emacs.sh`
```sh
#!/usr/bin/env bash

cd "$(dirname $0)" || exit 1

lab="/tmp/debug-emacs-playground"

git clone https://github.com/mattiasb/dired-hide-dotfiles /tmp/dired-hide-dotfiles

rm -rf "$lab"
mkdir -p "$lab"

touch "$lab/.abc"
emacs -Q -nw --load "debug.el" "$lab"
```
4. `./debug-emacs.sh`

You should see that file `.abc` is not hidden in `dired` buffer `/tmp/debug-emacs-playground`.

## possible solution
The funcction `dired-hide-dotfiles-mode` should be called by `dired-after-readin-hook` instead of `dired-mode-hook`.

https://github.com/mattiasb/dired-hide-dotfiles/blob/b715f643ec805b3b8aca334595e6589320f04a49/dired-hide-dotfiles.el#L66

To fix it, simply remove
```elisp
   ;; To hide dot-files by default 
   (dired-hide-dotfiles-mode)
``` 
from `my-dired-mode-hook`.

**Comment by mattiasb** [comment]
Hm. So is this basically about getting rid of output in `*Messages*` or is something breaking for you?

Looking at my own code now I realize that I add a hook on load which I probably should get rid off.

> The funcction dired-hide-dotfiles-mode should be called by dired-after-readin-hook instead of dired-mode-hook.

This makes no sense to me to be honest. That would toggle `dired-hide-dotfiles-mode` on each buffer revert right?

**Comment by snowman** [comment]
Yes, you are right, It'll result in an infinite loop. :heart:
