### ISSUE TITLE
Typo on message

### ISSUE THREAD

**Issue by Murgalha** [mattiasb/dired-hide-dotfiles#6]
Hi! I was using the package and noticed a small typo on the final message of hidden files: the format string contains a spare `s` so the final message is often `Hid X dotfiless`. I would make a PR with this fix, but I noticed 1 more thing I would like to discuss.

The `dired-plural-s` function used to put the plural `s` on the message checks only if the number of elements is 1, therefore when no files are hidden, the message is `Hid 0 dotfiles` (with the plural `s`). Should this case be left as-is (like normal dired) or reimplement a plural function that checks 0 and 1?

**Comment by mattiasb** [comment]
I think what one wants is:
```
Hid 0 dotfiles
Hid 1 dotfile
Hid 2 dotfiles
...
Hid <n> dotfiles
```
... because I think that's how you'd write it in English. I'm not a native speaker but I'm pretty confident that that's the case. :)

Note: I don't care about this myself but will happily take a PR (modulo code quality ofcourse)!

**Comment by mattiasb** [comment]
Actually I understood now. I just need to remove an `s`. I can do that myself. :D

**Comment by mattiasb** [comment]
Should be fixed [here](https://github.com/mattiasb/dired-hide-dotfiles/commit/efed61309765d6365bb448fc4c89b3bfa48db457).

**Comment by mattiasb** [comment]
Thanks!

**Comment by Murgalha** [comment]
Thank you for the correction

EDIT: It is indeed `0 dotfiles` in English. Sorry for the mistake.
