### ISSUE TITLE
This package can now be replaced by dired-omit-mode

### ISSUE THREAD

**Issue by ai-oleynikov** [mattiasb/dired-hide-dotfiles#8]
```elisp
(use-package dired
  :bind
  (:map dired-mode-map ("." . dired-omit-mode))
  :config
  (setq dired-omit-files (rx (seq bol ".")))
  ;; To hide dot-files by default
  :hook
  (dired-mode . dired-omit-mode))
```

**Comment by pprevos** [comment]
You need to activate dired-x first:

``` elisp
(use-package dired
  :ensure nil
  :bind
  (:map dired-mode-map ("." . dired-omit-mode))
  :custom
  (dired-omit-files (rx (seq bol ".")))
  :hook
  (dired-mode . dired-omit-mode)
  :init
  (with-eval-after-load 'dired (require 'dired-x)))
```

**Comment by mattiasb** [comment]
Sorry had missed this. I actually switched to using `dired-omit-mode` with this regex now. Thanks!

**Comment by mattiasb** [comment]
I added a deprecation notice. Will make the repository read-only eventually.

**Comment by pprevos** [comment]
A better regex to use is `(dired-omit-files "^\\.[a-zA-Z0-9]+")`, which retains the single and double dot entries so you can still move up the tree, but hides any filenames.

**Comment by mattiasb** [comment]
You could argue that, but it's subjective. I personally don't use the `..` to move up.

The regex I choose matches what this package does which was the goal.
